error: 앱 실행 오류로 findViewById를 주석 처리했다.
576-1740 TaskPersister system_server
E File error accessing recents directory (directory doesn't exist?).